name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go mods
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download

      - name: Run unit tests
        run: |
          make test

      - name: Build Subo
        run: |
          make subo

      - uses: actions/upload-artifact@v3
        with:
          name: subo
          path: ~/go/bin/subo
          if-no-files-found: error

  smoke:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - assemblyscript
          - rust
          - swift
          - tinygo
        include:
          - language: assemblyscript
            image: builder-as
          - language: rust
            image: builder-rs
          - language: swift
            image: builder-swift
          - language: tinygo
            image: builder-tinygo

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: subo
          path: ~/bin
      - run: |
          chmod +x $HOME/bin/subo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          file: builder/docker/${{ matrix.language }}/Dockerfile
          load: true
          tags: suborbital/${{ matrix.image }}:dev

      - name: Create runnable
        run: subo create runnable ${{ matrix.language }}-test --lang ${{ matrix.language }} --branch ${{ steps.branch-name.outputs.current_branch }}

      - name: Run subo build
        run: subo build ${{ matrix.language }}-test --builder-tag dev

      - name: Check TinyGo version number consistency
        if: matrix.language == 'tinygo'
        run: builder/docker/tinygo/smoke.sh

  # only run if reference is a tag
  release:
    if: startsWith(github.ref, 'refs/tags/v')

    needs: [lint, smoke, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go mods
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download

      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get committer name and email
        id: committer
        run: |
          echo "::set-output name=name::$(git --no-pager log -s --format="%an" -1)"
          echo "::set-output name=email::$(git --no-pager log -s --format="%ae" -1)"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_ACTOR_NAME: ${{ steps.committer.outputs.name }}
          GITHUB_ACTOR_EMAIL: ${{ steps.committer.outputs.email }}
