name: Testapalooza

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        golang: [1.17]

    name: Smoke
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.golang }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0

      - name: Build Subo
        run: |
          make subo

      - name: Create project and runnable
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          git config --global init.defaultBranch main
          subo create project smoketest
          subo create runnable rs-test --lang rust --dir ./smoketest
          subo create runnable swift-test --lang swift --dir ./smoketest
          subo create runnable as-test --lang assemblyscript --dir ./smoketest
          subo create runnable tinygo-test --lang tinygo --dir ./smoketest
          subo create runnable js-test --lang js --dir ./smoketest
          subo create runnable ts-test --lang ts --dir ./smoketest
          subo create runnable gr-test --lang gr --dir ./smoketest

      - name: Build project
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          subo build ./smoketest --builder-tag dev

      - name: Check TinyGo version number consistency
        run: |
          builder/docker/tinygo/sanity.sh
